---
version: 2
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
    - checkout
    - run:
        name: 'Get test data: ds114_test1'
        command: |
          if [[ ! -d ~/data/ds114_test1 ]]; \
            then wget -c -O ${HOME}/ds114_test1.tar "https://osf.io/download/zerfq/" && \
            mkdir -p ${HOME}/data && tar xf ${HOME}/ds114_test1.tar -C ${HOME}/data;
          fi
    - run:
        name: 'Get test data: ds114_test2'
        command: |
          if [[ ! -d ~/data/ds114_test2 ]]; \
            then wget -c -O ${HOME}/ds114_test2.tar "https://osf.io/download/eg4ma/" && \
            mkdir -p ${HOME}/data && tar xf ${HOME}/ds114_test2.tar -C ${HOME}/data;
          fi
    - run:
        name: Build Docker image
        command: |
          git describe --tags --always > version
          docker build -t bids/${CIRCLE_PROJECT_REPONAME,,} .
          mkdir -p ${HOME}/docker
          docker save "bids/${CIRCLE_PROJECT_REPONAME,,}" > ~/docker/image.tar
    - persist_to_workspace:
        root: /home/circleci
        paths:
        - data/ds114_test1
        - data/ds114_test2
        - docker/image.tar

  test:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
    - attach_workspace:
        at: /tmp/workspace

    - run: mkdir -p ${HOME}/outputs1
    - run: mkdir -p ${HOME}/outputs2

    - run:
        name: print version
        command: |
          docker load -i /tmp/workspace/docker/image.tar
          docker run -ti --rm --read-only \
            -v /tmp/workspace/data/ds114_test1:/bids_dataset \
            -v ${HOME}/outputs1:/outputs \
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                /bids_dataset \
                /outputs participant --version

    - run:
        name: participant level tests for dataset with no session level - participant << parameters.participant_label >>
        command: |
          docker load -i /tmp/workspace/docker/image.tar
          docker run -ti --rm --read-only \
            -v /tmp/workspace/data/ds114_test1:/bids_dataset \
            -v ${HOME}/outputs1:/outputs \
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                /bids_dataset /outputs participant --participant_label << parameters.participant_label >> --stages CSE
        no_output_timeout: 6h

    - run:
        command: |
          docker load -i /tmp/workspace/docker/image.tar
          docker run -ti --rm --read-only \
            -v /tmp/workspace/data/ds114_test1:/bids_dataset \
            -v ${HOME}/outputs1:/outputs \
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                /bids_dataset /outputs participant --participant_label << parameters.participant_label >> --stages BDP
        no_output_timeout: 6h

    - run:
        command: |
          docker load -i /tmp/workspace/docker/image.tar
          docker run -ti --rm --read-only \
            -v /tmp/workspace/data/ds114_test1:/bids_dataset \
            -v ${HOME}/outputs1:/outputs \
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                /bids_dataset /outputs participant --participant_label << parameters.participant_label >> --stages CSE BDP
        no_output_timeout: 6h

    - run:
        name: participant level tests for dataset with session level - participant << parameters.participant_label >>
        command: |
          docker load -i /tmp/workspace/docker/image.tar
          docker run -ti --rm --read-only \
            -v /tmp/workspace/data/ds114_test2:/bids_dataset \
            -v ${HOME}/outputs2:/outputs \
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                /bids_dataset /outputs participant --participant_label << parameters.participant_label >> --stages CSE
        no_output_timeout: 6h

    - run:
        command: |
          docker load -i /tmp/workspace/docker/image.tar
          docker run -ti --rm --read-only \
            -v /tmp/workspace/data/ds114_test2:/bids_dataset \
            -v ${HOME}/outputs2:/outputs \
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                /bids_dataset /outputs participant --participant_label << parameters.participant_label >> --stages BDP
        no_output_timeout: 6h

    - run:
        command: |
          docker load -i /tmp/workspace/docker/image.tar
          docker run -ti --rm --read-only \
            -v /tmp/workspace/data/ds114_test2:/bids_dataset \
            -v ${HOME}/outputs2:/outputs \
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                /bids_dataset /outputs participant --participant_label << parameters.participant_label >> --stages CSE BDP
        no_output_timeout: 6h

  deploy:
    docker:
    - image: circleci/buildpack-deps:stretch
    steps:
    - attach_workspace:
        at: /tmp/workspace

    - run: docker load -i /tmp/workspace/docker/image.tar
    - run:
        name: push to dockerhub
        command: |
          docker login --username ${DOCKER_USER} --password ${DOCKER_PASS}
          docker push bids/${CIRCLE_PROJECT_REPONAME,,}:latest
          if [[ -n "${CIRCLE_TAG}" ]]; then
            docker tag bids/${CIRCLE_PROJECT_REPONAME,,} bids/${CIRCLE_PROJECT_REPONAME,,}:${CIRCLE_TAG}
            docker push bids/${CIRCLE_PROJECT_REPONAME,,}:${CIRCLE_TAG}
          fi
workflows:
  version: 2
  build-test-deploy:
    jobs:
    - build
    - test:
        requires:
        - build
        matrix:
          parameters:
            participant_label: ['01', '02']
    - deploy:
        requires:
        - test
        filters:
          tags:
            only: /.*/
# VS Code Extension Version: 1.5.1
