---
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
    - checkout
    - run:
        name: Get test data ds114_test*
        command: |
          wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/utils/get_data_from_osf.sh
          bash get_data_from_osf.sh ds114_test1
          bash get_data_from_osf.sh ds114_test2
    - run:
        name: Build Docker image
        command: |
          wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/circleci/build_docker.sh
          bash build_docker.sh
    - persist_to_workspace:
        root: /home/circleci
        paths:
        - data/ds114_test1
        - data/ds114_test2
        - docker/image.tar

  test:
    machine:
      image: ubuntu-2204:2022.10.2

    parameters:
      participant:
        type: string
      dataset:
        type: string

    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run: docker load -i /tmp/workspace/docker/image.tar

    - run: mkdir -p ${HOME}/outputs<< parameters.participant >>

    - run:
        name: print version
        command: |
          docker run -ti --rm \
            -v /tmp/workspace/data/ds114_test<< parameters.dataset >>:/bids_dataset \
            -v ${HOME}/outputs<< parameters.participant >>:/outputs \
            -v /tmp:/tmp \
            -v /var/tmp:/var/tmp \
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                /bids_dataset \
                /outputs \
                participant \
                --version

    - run:
        name: participant level CSE tests - participant << parameters.participant >>
        command: |
          docker run -ti --rm \
            -v /tmp/workspace/data/ds114_test<< parameters.dataset >>:/bids_dataset \
            -v ${HOME}/outputs<< parameters.participant >>:/outputs \
            # -v /tmp:/tmp \
            # -v /var/tmp:/var/tmp \            
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                /bids_dataset \
                /outputs \
                participant \
                --participant_label << parameters.participant >> \
                --stages CSE \
                --cache /outputs
        no_output_timeout: 6h

    - run:
        name: participant level BDP tests - participant << parameters.participant >>
        command: |
          docker run -ti --rm \
            -v /tmp/workspace/data/ds114_test<< parameters.dataset >>:/bids_dataset \
            -v ${HOME}/outputs<< parameters.participant >>:/outputs \
            # -v /tmp:/tmp \
            # -v /var/tmp:/var/tmp \                
              bids/${CIRCLE_PROJECT_REPONAME,,} \
                /bids_dataset \
                /outputs \
                participant \
                --participant_label << parameters.participant >> \
                --stages CSE BDP \
                --cache /outputs
        no_output_timeout: 6h

  deploy:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
    - attach_workspace:
        at: /tmp/workspace
    - run: docker load -i /tmp/workspace/docker/image.tar
    - run:
        name: push to dockerhub
        command: |
          wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/circleci/push_docker.sh
          bash push_docker.sh

workflows:
  build-test-deploy:
    jobs:
    - build
    - test:
        requires:
        - build
        matrix:
          parameters:
            participant: ['01', '02']
            dataset: ['1', '2']
    - deploy:
        context:
        - dockerhub
        requires:
        - test
        filters:
          tags:
            only: /.*/


# VS Code Extension Version: 1.5.1
