---
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
      - checkout
      - run:
          name: Get test data ds114_test1
          command: |
            wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/utils/get_data_from_osf.sh
            bash get_data_from_osf ds114_test1
      - run:
          name: Get test data ds114_test2
          command: |
            wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/utils/get_data_from_osf.sh
            bash get_ds114_test2.sh
      - run:
          name: Build Docker image
          command: |
            wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/circleci/build_docker.sh
            bash build_docker.sh
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - data/ds114_test1
            - data/ds114_test2
            - docker/image.tar

  test:
    machine:
      image: ubuntu-2204:2022.10.2

    parameters:
      participant:
        type: string

    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run: mkdir -p ${HOME}/outputs1
      - run: mkdir -p ${HOME}/outputs2

      - run:
          name: print version
          command: |
            docker load -i /tmp/workspace/docker/image.tar
            docker run -ti --rm --read-only \
              -v /tmp/workspace/data/ds114_test1:/bids_dataset \
              -v ${HOME}/outputs1:/outputs \
                bids/${CIRCLE_PROJECT_REPONAME,,} \
                  /bids_dataset \
                  /outputs participant --version

      - run:
          name:
            "participant level tests for dataset with no session level - participant << parameters.participant >>"
          command: |
            docker load -i /tmp/workspace/docker/image.tar
            docker run -ti --rm --read-only \
              -v /tmp/workspace/data/ds114_test1:/bids_dataset \
              -v ${HOME}/outputs1:/outputs \
                bids/${CIRCLE_PROJECT_REPONAME,,} \
                  /bids_dataset /outputs participant --participant_label << parameters.participant >> --stages CSE
          no_output_timeout: 6h

      - run:
          command: |
            docker load -i /tmp/workspace/docker/image.tar
            docker run -ti --rm --read-only \
              -v /tmp/workspace/data/ds114_test1:/bids_dataset \
              -v ${HOME}/outputs1:/outputs \
                bids/${CIRCLE_PROJECT_REPONAME,,} \
                  /bids_dataset /outputs participant --participant_label << parameters.participant >> --stages BDP
          no_output_timeout: 6h

      - run:
          command: |
            docker load -i /tmp/workspace/docker/image.tar
            docker run -ti --rm --read-only \
              -v /tmp/workspace/data/ds114_test1:/bids_dataset \
              -v ${HOME}/outputs1:/outputs \
                bids/${CIRCLE_PROJECT_REPONAME,,} \
                  /bids_dataset /outputs participant --participant_label << parameters.participant >> --stages CSE BDP
          no_output_timeout: 6h

      - run:
          name:
            "participant level tests for dataset with session level - participant << parameters.participant >>"
          command: |
            docker load -i /tmp/workspace/docker/image.tar
            docker run -ti --rm --read-only \
              -v /tmp/workspace/data/ds114_test2:/bids_dataset \
              -v ${HOME}/outputs2:/outputs \
                bids/${CIRCLE_PROJECT_REPONAME,,} \
                  /bids_dataset /outputs participant --participant_label << parameters.participant >> --stages CSE
          no_output_timeout: 6h

      - run:
          command: |
            docker load -i /tmp/workspace/docker/image.tar
            docker run -ti --rm --read-only \
              -v /tmp/workspace/data/ds114_test2:/bids_dataset \
              -v ${HOME}/outputs2:/outputs \
                bids/${CIRCLE_PROJECT_REPONAME,,} \
                  /bids_dataset /outputs participant --participant_label << parameters.participant >> --stages BDP
          no_output_timeout: 6h

      - run:
          command: |
            docker load -i /tmp/workspace/docker/image.tar
            docker run -ti --rm --read-only \
              -v /tmp/workspace/data/ds114_test2:/bids_dataset \
              -v ${HOME}/outputs2:/outputs \
                bids/${CIRCLE_PROJECT_REPONAME,,} \
                  /bids_dataset /outputs participant --participant_label << parameters.participant >> --stages CSE BDP
          no_output_timeout: 6h

  deploy:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: docker load -i /tmp/workspace/docker/image.tar
      - run:
          name: push to dockerhub
          command: |
            wget https://raw.githubusercontent.com/bids-apps/maintenance-tools/main/circleci/push_docker.sh
            bash push_docker.sh

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
          matrix:
            parameters:
              participant: ["01", "02"]
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/

